In [8]:
import pandas as pd

# Load the file to examine its structure
file_path = 'C:/Postgrad/Courses/Fall_2024/6907 Advanced Interaction Techniques/Project/hand-gesture-recognition-mediapipe-main - Copy 1/model/keypoint_classifier/keypoint.csv'
data = pd.read_csv(file_path, header = None)

# Display the first few rows to understand its structure
data.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,0,0,-0.184564,-0.077181,-0.312081,-0.241611,-0.369128,-0.392617,-0.449664,...,0.057047,-0.949664,0.154362,-0.432886,0.191275,-0.580537,0.211409,-0.687919,0.231544,-0.791946
1,0,0,0,-0.178082,-0.068493,-0.315068,-0.222603,-0.386986,-0.369863,-0.476027,...,0.037671,-0.934932,0.140411,-0.438356,0.171233,-0.585616,0.198630,-0.681507,0.226027,-0.777397
2,0,0,0,-0.182759,-0.065517,-0.313793,-0.220690,-0.386207,-0.365517,-0.472414,...,0.041379,-0.937931,0.141379,-0.434483,0.175862,-0.582759,0.203448,-0.679310,0.227586,-0.775862
3,0,0,0,-0.182759,-0.068966,-0.317241,-0.224138,-0.389655,-0.368966,-0.479310,...,0.037931,-0.941379,0.137931,-0.437931,0.172414,-0.582759,0.200000,-0.682759,0.220690,-0.779310
4,0,0,0,-0.182759,-0.068966,-0.317241,-0.224138,-0.393103,-0.368966,-0.479310,...,0.037931,-0.941379,0.137931,-0.437931,0.172414,-0.582759,0.196552,-0.682759,0.213793,-0.782759

In [10]:
# The first column appears to be the first column named as '0' in this dataset.
# I'll perform the transformation requested: change 0s to 1s, 1s to 2s, etc., in the first column.

# Increment each value by 1 in the first column
data[0] = data[0] + 1

# Save the updated file and display it to the user
updated_file_path = 'C:/Postgrad/Courses/Fall_2024/6907 Advanced Interaction Techniques/Project/hand-gesture-recognition-mediapipe-main - Copy 1/model/keypoint_classifier/keypoint_updated.csv'
data.to_csv(updated_file_path, index=False)

updated_file_path

'C:/Postgrad/Courses/Fall_2024/6907 Advanced Interaction Techniques/Project/hand-gesture-recognition-mediapipe-main - Copy 1/model/keypoint_classifier/keypoint_updated.csv'